cd ./src/Guide/
python3 Guide_1.py
cd ../../
cd ./src/Aug
python3 Data_augmentation_0.py
python3 Data_augmentation_1.py
python3 Data_augmentation_2.py
python3 Data_augmentation_3.py
python3 Data_augmentation_4.py
python3 Data_augmentation_5.py
python3 Data_augmentation_6.py
python3 Data_augmentation_7.py
python3 Data_augmentation_8.py
python3 Data_augmentation_9.py
cd ../../
cd ./src/Guide
python3 Guide_2.py
cd ../../
cd ./src/SufferMing
python3 train8s_MAXv6gen3_upload_0.py
python3 train8s_MAXv6gen3_upload_1.py
python3 train8s_MAXv6gen3_upload_2.py
python3 train8s_MAXv6gen3_upload_3.py
python3 train8s_MAXv6gen3_upload_4.py
python3 train8s_MAXv6gen3_upload_5.py
python3 train8s_MAXv6gen3_upload_6.py
python3 train8s_MAXv6gen3_upload_7.py
python3 train8s_MAXv6gen3_upload_8.py
python3 train8s_MAXv6gen3_upload_9.py
python3 train8s_MAXv6gen3_upload_10.py
python3 train8s_MAXv6gen3_upload_11.py
python3 train8s_MAXv6gen3_upload_12.py
python3 train8s_MAXv6gen3_upload_13.py
cd ../../
cd ./src/Guide
python3 Guide_3.py
cd ../../
cd ./src/SufferMing
python3 Ensemble.py
python3 FileArrangement.py
cd ../../
cd ./src/Guide
python3 Guide_4.py
cd ../../
